#!/bin/bash

# path for systemmd-timers and cron jobs
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# cli tool to compress and backup data folders
delete_archives() {
    # log folder argument; removing trailing slash (if there) for tar command's dirname and basename functionality below
    local user_archive_folder="${1%/}"

    # checking if an argument has been passed in the terminal; if no arg passed fail otherwise continue with script
    if [[ -z "$user_archive_folder" ]]; then
        echo -e "\n🚨 \e[31mKindly provide an archive folder!" 
        return 1
    fi

    # checking if directory given exists
    if [[ ! -d "$user_archive_folder" ]]; then
        echo -e "\n🚨 \e[31mThe directory you passed doesn't exist. Kindly check your path!"
        return 1
    fi

    # already existing in the backup folder displaying history of all backed up archives
    archive_log_file="$user_archive_folder/archive-logs-history.log"

    # placing files to delete in a variable
    tarfiles_to_delete=$(find "$user_archive_folder" -type f -name "*.tar.gz" -mmin +3)

    # if there are files older than 3 days delete then else echo no files found older than 3 days
    if [[ -n "$tarfiles_to_delete" ]]; then
        echo -e "🚮 Deleting old archives, please wait..."
        # creating if doesn't exist, archive log file in /var/backups/my-logs-backup-folder
        touch "$archive_log_file"
        # updating archive log file of the new compression process
        echo -e "Here is the list of tar files being deleted:\n$tarfiles_to_delete" >> "$archive_log_file"
        # delete all archives (tar.gz) in user_archive_folder older than 3 days
        find "$user_archive_folder" -type f -name "*.tar.gz" -mmin +3 -print0 | xargs -0 rm
        echo "✅ Sucess: Old archives deleted"
        echo "🚮 Cleanup Sucess: [$(date +%Y%m%d_%H%M%S)]: Backups older than 3 days deleted!" >> "$archive_log_file"
    else
        echo "No files older than 3 days found."
    fi

    # error checking
    if [[ $? -ne 0 ]]; then
        echo "❌ Cleanup failed with exit code $?"
        return 1
    fi
}

# running function with folder passed arg in terminal
delete_archives "$1"

# learn about xargs
